<a href="https://colab.research.google.com/github/olakursri/DSML/blob/pandas/9_Pandas_5_Dec24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!gdown 173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ

Downloading...
From: https://drive.google.com/uc?id=173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ
To: /content/Pfizer_1.csv
100% 1.51k/1.51k [00:00<00:00, 4.23MB/s]

In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv('Pfizer_1.csv')

data_melt = pd.melt(data,id_vars = ['Date', 'Drug_Name', 'Parameter'],
            var_name = "time",
            value_name = 'reading')

data_tidy = data_melt.pivot(index=['Date','time', 'Drug_Name'],
                                        columns = 'Parameter',
                                        values='reading')
data_tidy = data_tidy.reset_index()
data_tidy.columns.name = None

In [ ]:
data.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

In [ ]:
data_melt.head()

         Date                Drug_Name    Parameter     time  reading
0  15-10-2020  diltiazem hydrochloride  Temperature  1:30:00     23.0
1  15-10-2020  diltiazem hydrochloride     Pressure  1:30:00     12.0
2  15-10-2020      docetaxel injection  Temperature  1:30:00      NaN
3  15-10-2020      docetaxel injection     Pressure  1:30:00      NaN
4  15-10-2020   ketamine hydrochloride  Temperature  1:30:00     24.0

In [ ]:
data_tidy.head()

         Date      time                Drug_Name  Pressure  Temperature
0  15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0
1  15-10-2020  10:30:00      docetaxel injection      26.0         23.0
2  15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0
3  15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0
4  15-10-2020  11:30:00      docetaxel injection      29.0         25.0

In [ ]:
data_tidy['Temperature'].min(), data_tidy['Temperature'].max()

(8.0, 58.0)

In [ ]:
temp_points = [5, 20, 35, 50, 60]
temp_labels = ['low', 'medium', 'high', 'very_high']
data_tidy['temp_cat'] = pd.cut(data_tidy['Temperature'], bins=temp_points, labels=temp_labels)
data_tidy

,Date,time,Drug_Name,Pressure,Temperature,temp_cat
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0,low
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0,medium
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0,medium
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0,low
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0,medium
...,...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0,low
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0,low
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0,low
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0,low
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0,medium

In [ ]:
pd.cut(data_tidy['Temperature'], bins=temp_points)

0       (5, 20]
1      (20, 35]
2      (20, 35]
3       (5, 20]
4      (20, 35]
         ...
103     (5, 20]
104     (5, 20]
105     (5, 20]
106     (5, 20]
107    (20, 35]
Name: Temperature, Length: 108, dtype: category
Categories (4, interval[int64, right]): [(5, 20] < (20, 35] < (35, 50] < (50, 60]]

In [ ]:
data.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

In [ ]:
type(None)

NoneType

In [ ]:
type(np.nan)

float

In [ ]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [ ]:
pd.Series(['1', np.nan, '2', '3', None])

0       1
1     NaN
2       2
3       3
4    None
dtype: object

In [ ]:
pd.Series(['1', 2, np.nan, None])

0       1
1       2
2     NaN
3    None
dtype: object

In [ ]:
data.isna()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
3,False,False,False,True,False,False,True,False,False,True,True,False,False,False,False
4,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
5,False,False,False,False,True,True,False,True,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
11,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
data.isna().sum()

Date         0
Drug_Name    0
Parameter    0
1:30:00      2
2:30:00      2
3:30:00      6
4:30:00      4
5:30:00      2
6:30:00      0
7:30:00      2
8:30:00      4
9:30:00      2
10:30:00     0
11:30:00     2
12:30:00     0
dtype: int64

In [ ]:
data.isna().sum(axis=1)

0     1
1     1
2     4
3     4
4     3
5     3
6     1
7     1
8     1
9     1
10    2
11    2
12    1
13    1
14    0
15    0
16    0
17    0
dtype: int64

In [ ]:
data.dropna()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
data.dropna(axis=1)

,Date,Drug_Name,Parameter,6:30:00,10:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,22,20,21
1,15-10-2020,diltiazem hydrochloride,Pressure,14,18,20
2,15-10-2020,docetaxel injection,Temperature,18,23,25
3,15-10-2020,docetaxel injection,Pressure,23,26,28
4,15-10-2020,ketamine hydrochloride,Temperature,26,22,20
5,15-10-2020,ketamine hydrochloride,Pressure,9,9,11
6,16-10-2020,diltiazem hydrochloride,Temperature,38,40,42
7,16-10-2020,diltiazem hydrochloride,Pressure,23,24,27
8,16-10-2020,docetaxel injection,Temperature,49,56,58
9,16-10-2020,docetaxel injection,Pressure,27,28,30
10,16-10-2020,ketamine hydrochloride,Temperature,12,13,15
11,16-10-2020,ketamine hydrochloride,Pressure,15,16,18
12,17-10-2020,diltiazem hydrochloride,Temperature,16,14,10
13,17-10-2020,diltiazem hydrochloride,Pressure,8,11,14
14,17-10-2020,docetaxel injection,Temperature,17,21,23
15,17-10-2020,docetaxel injection,Pressure,23,28,28
16,17-10-2020,ketamine hydrochloride,Temperature,18,22,24
17,17-10-2020,ketamine hydrochloride,Pressure,12,13,15

In [ ]:
data.isnull().sum()

Date         0
Drug_Name    0
Parameter    0
1:30:00      2
2:30:00      2
3:30:00      6
4:30:00      4
5:30:00      2
6:30:00      0
7:30:00      2
8:30:00      4
9:30:00      2
10:30:00     0
11:30:00     2
12:30:00     0
dtype: int64

In [ ]:
data.fillna(0)

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,0.0,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,0.0,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,0.0,17.0,18.0,0.0,17.0,18,0.0,0.0,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,0.0,22.0,22.0,0.0,22.0,23,0.0,0.0,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,0.0,0.0,27.0,0.0,26,25.0,24.0,23.0,22,21.0,20
5,15-10-2020,ketamine hydrochloride,Pressure,8.0,0.0,0.0,7.0,0.0,9,10.0,11.0,10.0,9,9.0,11
6,16-10-2020,diltiazem hydrochloride,Temperature,34.0,35.0,36.0,36.0,37.0,38,37.0,38.0,39.0,40,0.0,42
7,16-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,21.0,22.0,23,24.0,25.0,25.0,24,0.0,27
8,16-10-2020,docetaxel injection,Temperature,46.0,47.0,0.0,48.0,48.0,49,50.0,52.0,55.0,56,57.0,58
9,16-10-2020,docetaxel injection,Pressure,23.0,24.0,0.0,25.0,26.0,27,28.0,29.0,28.0,28,29.0,30
10,16-10-2020,ketamine hydrochloride,Temperature,8.0,9.0,10.0,0.0,11.0,12,12.0,11.0,0.0,13,14.0,15
11,16-10-2020,ketamine hydrochloride,Pressure,12.0,12.0,13.0,0.0,15.0,15,15.0,15.0,0.0,16,17.0,18
12,17-10-2020,diltiazem hydrochloride,Temperature,20.0,19.0,19.0,18.0,17.0,16,15.0,0.0,13.0,14,11.0,10
13,17-10-2020,diltiazem hydrochloride,Pressure,3.0,4.0,4.0,4.0,6.0,8,9.0,0.0,9.0,11,13.0,14
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [ ]:
data['2:30:00'].fillna(0)

0     22.0
1     13.0
2     17.0
3     22.0
4      0.0
5      0.0
6     35.0
7     19.0
8     47.0
9     24.0
10     9.0
11    12.0
12    19.0
13     4.0
14    13.0
15    22.0
16    14.0
17     9.0
Name: 2:30:00, dtype: float64

In [ ]:
data['2:30:00'].mean()

np.float64(18.8125)

In [ ]:
data['2:30:00'].fillna(data['2:30:00'].mean())

0     22.0000
1     13.0000
2     17.0000
3     22.0000
4     18.8125
5     18.8125
6     35.0000
7     19.0000
8     47.0000
9     24.0000
10     9.0000
11    12.0000
12    19.0000
13     4.0000
14    13.0000
15    22.0000
16    14.0000
17     9.0000
Name: 2:30:00, dtype: float64

In [ ]:
data['Drug_Name'].value_counts()

Drug_Name
diltiazem hydrochloride    6
docetaxel injection        6
ketamine hydrochloride     6
Name: count, dtype: int64

In [ ]:
data_tidy.isna().sum()

Date            0
time            0
Drug_Name       0
Pressure       13
Temperature    13
temp_cat       13
dtype: int64

In [ ]:
def temp_mean(x):
  x['Temp_avg'] = x['Temperature'].mean()
  return x

data_tidy = data_tidy.groupby('Drug_Name', group_keys=False).apply(temp_mean)
data_tidy

<ipython-input-35-a1692cd77d20>:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_tidy = data_tidy.groupby('Drug_Name', group_keys=False).apply(temp_mean)

,Date,time,Drug_Name,Pressure,Temperature,temp_cat,Temp_avg
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0,low,24.848485
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0,medium,30.387097
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0,medium,17.709677
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0,low,24.848485
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0,medium,30.387097
...,...,...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0,low,30.387097
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0,low,17.709677
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0,low,24.848485
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0,low,30.387097
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0,medium,17.709677

In [ ]:
data_tidy.groupby('Drug_Name', group_keys=False).apply(temp_mean)

<ipython-input-36-4f1d4da37115>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_tidy.groupby('Drug_Name', group_keys=False).apply(temp_mean)

,Date,time,Drug_Name,Pressure,Temperature,temp_cat,Temp_avg
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0,low,24.848485
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0,medium,30.387097
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0,medium,17.709677
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0,low,24.848485
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0,medium,30.387097
...,...,...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0,low,30.387097
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0,low,17.709677
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0,low,24.848485
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0,low,30.387097
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0,medium,17.709677

In [ ]:
data_tidy['Temperature'].fillna(data_tidy['Temp_avg'], inplace=True)
data_tidy

<ipython-input-41-779893298178>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_tidy['Temperature'].fillna(data_tidy['Temp_avg'], inplace=True)

,Date,time,Drug_Name,Pressure,Temperature,temp_cat,Temp_avg
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0,low,24.848485
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0,medium,30.387097
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0,medium,17.709677
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0,low,24.848485
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0,medium,30.387097
...,...,...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0,low,30.387097
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0,low,17.709677
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0,low,24.848485
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0,low,30.387097
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0,medium,17.709677

In [ ]:
data_tidy['Temperature'].isnull().sum()

np.int64(0)

In [ ]:
data_tidy['Temperature']

0      20.0
1      23.0
2      22.0
3      20.0
4      25.0
       ...
103    19.0
104    20.0
105    13.0
106    20.0
107    21.0
Name: Temperature, Length: 108, dtype: float64

In [ ]:
def pre_mean(x):
  x['Pre_avg'] = x['Pressure'].mean()
  return x

data_tidy = data_tidy.groupby('Drug_Name', group_keys=False).apply(pre_mean)
data_tidy['Pressure'].fillna(data_tidy['Pre_avg'], inplace=True)
data_tidy

<ipython-input-45-8a4474f98d68>:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_tidy = data_tidy.groupby('Drug_Name', group_keys=False).apply(pre_mean)
<ipython-input-45-8a4474f98d68>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_tidy['Pressure'].fillna(data_tidy['Pre_avg'], inplace=True)

,Date,time,Drug_Name,Pressure,Temperature,temp_cat,Temp_avg,Pre_avg
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0,low,24.848485,15.424242
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0,medium,30.387097,25.483871
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0,medium,17.709677,11.935484
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0,low,24.848485,15.424242
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0,medium,30.387097,25.483871
...,...,...,...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0,low,30.387097,25.483871
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0,low,17.709677,11.935484
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0,low,24.848485,15.424242
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0,low,30.387097,25.483871
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0,medium,17.709677,11.935484

In [ ]:
data_tidy.isnull().sum()

Date            0
time            0
Drug_Name       0
Pressure        0
Temperature     0
temp_cat       13
Temp_avg        0
Pre_avg         0
dtype: int64

In [ ]:
sample = pd.Series(['1', '2', '3', np.nan, None])
# sample
sample.fillna(0)

0    1
1    2
2    3
3    0
4    0
dtype: object

In [ ]:
data_tidy.loc[data_tidy['Drug_Name'].str.contains('hydrochloride')]

,Date,time,Drug_Name,Pressure,Temperature,temp_cat,Temp_avg,Pre_avg
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.000000,20.000000,low,24.848485,15.424242
2,15-10-2020,10:30:00,ketamine hydrochloride,9.000000,22.000000,medium,17.709677,11.935484
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.000000,20.000000,low,24.848485,15.424242
5,15-10-2020,11:30:00,ketamine hydrochloride,9.000000,21.000000,medium,17.709677,11.935484
6,15-10-2020,12:30:00,diltiazem hydrochloride,20.000000,21.000000,medium,24.848485,15.424242
...,...,...,...,...,...,...,...,...
101,17-10-2020,7:30:00,ketamine hydrochloride,12.000000,19.000000,low,17.709677,11.935484
102,17-10-2020,8:30:00,diltiazem hydrochloride,15.424242,24.848485,NaN,24.848485,15.424242
104,17-10-2020,8:30:00,ketamine hydrochloride,11.000000,20.000000,low,17.709677,11.935484
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.000000,13.000000,low,24.848485,15.424242
107,17-10-2020,9:30:00,ketamine hydrochloride,12.000000,21.000000,medium,17.709677,11.935484

In [ ]:
data_tidy['Date'].str.split('-')

0      [15, 10, 2020]
1      [15, 10, 2020]
2      [15, 10, 2020]
3      [15, 10, 2020]
4      [15, 10, 2020]
            ...
103    [17, 10, 2020]
104    [17, 10, 2020]
105    [17, 10, 2020]
106    [17, 10, 2020]
107    [17, 10, 2020]
Name: Date, Length: 108, dtype: object

In [ ]:
data_tidy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108 entries, 0 to 107
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         108 non-null    object
 1   time         108 non-null    object
 2   Drug_Name    108 non-null    object
 3   Pressure     108 non-null    float64
 4   Temperature  108 non-null    float64
 5   temp_cat     95 non-null     category
 6   Temp_avg     108 non-null    float64
 7   Pre_avg      108 non-null    float64
dtypes: category(1), float64(4), object(3)
memory usage: 11.1+ KB

In [ ]:
data_tidy['Date'].str.split('-')[2][2]

'2020'

In [ ]:
data_tidy['Date'].str.split('-').apply(lambda x: x[2])

0      2020
1      2020
2      2020
3      2020
4      2020
       ...
103    2020
104    2020
105    2020
106    2020
107    2020
Name: Date, Length: 108, dtype: object

In [ ]:
data_tidy['timestamp'] = data_tidy['Date'] + ' '+ data_tidy['time']
data_tidy

,Date,time,Drug_Name,Pressure,Temperature,temp_cat,Temp_avg,Pre_avg,timestamp
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0,low,24.848485,15.424242,15-10-2020 10:30:00
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0,medium,30.387097,25.483871,15-10-2020 10:30:00
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0,medium,17.709677,11.935484,15-10-2020 10:30:00
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0,low,24.848485,15.424242,15-10-2020 11:30:00
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0,medium,30.387097,25.483871,15-10-2020 11:30:00
...,...,...,...,...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0,low,30.387097,25.483871,17-10-2020 8:30:00
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0,low,17.709677,11.935484,17-10-2020 8:30:00
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0,low,24.848485,15.424242,17-10-2020 9:30:00
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0,low,30.387097,25.483871,17-10-2020 9:30:00
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0,medium,17.709677,11.935484,17-10-2020 9:30:00

In [ ]:
data_tidy['timestamp'] = pd.to_datetime(data_tidy['timestamp'])
data_tidy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108 entries, 0 to 107
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         108 non-null    object
 1   time         108 non-null    object
 2   Drug_Name    108 non-null    object
 3   Pressure     108 non-null    float64
 4   Temperature  108 non-null    float64
 5   temp_cat     95 non-null     category
 6   Temp_avg     108 non-null    float64
 7   Pre_avg      108 non-null    float64
 8   timestamp    108 non-null    datetime64[ns]
dtypes: category(1), datetime64[ns](1), float64(4), object(3)
memory usage: 12.0+ KB

In [ ]:
ts = data_tidy['timestamp'][0]
ts

Timestamp('2020-10-15 10:30:00')

In [ ]:
ts.day, ts.month, ts.year, ts.hour, ts.month_name(), ts.day_name()

(15, 10, 2020, 10, 'October', 'Thursday')

In [ ]:
data_tidy['timestamp'].dt.day_name()

0      Thursday
1      Thursday
2      Thursday
3      Thursday
4      Thursday
         ...
103    Saturday
104    Saturday
105    Saturday
106    Saturday
107    Saturday
Name: timestamp, Length: 108, dtype: object

In [ ]:
data_tidy['timestamp'][0].strftime('%Y-%m-%d')

'2020-10-15'

In [ ]:
df = pd.DataFrame([[1, '2020-01-01'], [2, '1998-01-12'], [3, '2012-11-05'],
                   [4, '2000-12-03'], [5, '1960-04-23'], [6, '2008-08-15']],
                    columns=["ID", "birth_dates"])

# df.iloc[2]['birth_dates'].year - df.iloc[1]['birth_dates'].year
df

   ID birth_dates
0   1  2020-01-01
1   2  1998-01-12
2   3  2012-11-05
3   4  2000-12-03
4   5  1960-04-23
5   6  2008-08-15

In [ ]:
data_tidy.to_csv('pfizer_tidy.csv', sep=',', index=False)

In [ ]:
data_tidy['flag'] = data_tidy.groupby('Drug_Name')['Pressure'].mean()
data_tidy

,Date,time,Drug_Name,Pressure,Temperature,temp_cat,Temp_avg,Pre_avg,timestamp,flag
0,15-10-2020,10:30:00,diltiazem hydrochloride,18.0,20.0,low,24.848485,15.424242,2020-10-15 10:30:00,NaN
1,15-10-2020,10:30:00,docetaxel injection,26.0,23.0,medium,30.387097,25.483871,2020-10-15 10:30:00,NaN
2,15-10-2020,10:30:00,ketamine hydrochloride,9.0,22.0,medium,17.709677,11.935484,2020-10-15 10:30:00,NaN
3,15-10-2020,11:30:00,diltiazem hydrochloride,19.0,20.0,low,24.848485,15.424242,2020-10-15 11:30:00,NaN
4,15-10-2020,11:30:00,docetaxel injection,29.0,25.0,medium,30.387097,25.483871,2020-10-15 11:30:00,NaN
...,...,...,...,...,...,...,...,...,...,...
103,17-10-2020,8:30:00,docetaxel injection,26.0,19.0,low,30.387097,25.483871,2020-10-17 08:30:00,NaN
104,17-10-2020,8:30:00,ketamine hydrochloride,11.0,20.0,low,17.709677,11.935484,2020-10-17 08:30:00,NaN
105,17-10-2020,9:30:00,diltiazem hydrochloride,9.0,13.0,low,24.848485,15.424242,2020-10-17 09:30:00,NaN
106,17-10-2020,9:30:00,docetaxel injection,27.0,20.0,low,30.387097,25.483871,2020-10-17 09:30:00,NaN
107,17-10-2020,9:30:00,ketamine hydrochloride,12.0,21.0,medium,17.709677,11.935484,2020-10-17 09:30:00,NaN